// <auto-generated />
using System;
using System.Collections.Generic;
using KasraLoan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KasraLoan.Infrastructure.Migrations
{
    [DbContext(typeof(KasraLoanDbContext))]
    [Migration("20260825111653_AddNationalIdToEmployee")]
    partial class AddNationalIdToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KasraLoan.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LoanRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LoanRequestId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<string>>("AdditionalPhoneNumbers")
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("EmploymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSeniorAdmin")
                        .HasColumnType("boolean");

                    b.Property<int?>("JobPositionId")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ManagedLoanTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("MarriageDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MonthlySalary")
                        .HasColumnType("bigint");

                    b.Property<bool>("MustResetPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NationalId")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobPositionId");

                    b.HasIndex("ManagedLoanTypeId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.EmployeeScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasLoanPermissionOverride")
                        .HasColumnType("boolean");

                    b.Property<int?>("ManualOverrideScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OverriddenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PermissionGrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeScores");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.EmploymentStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "ChangedAt");

                    b.ToTable("EmploymentStatusChanges");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.InstallmentPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ChequeBankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ChequeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChequeImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ChequeNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GatewayAuthority")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GatewayExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GatewayRefId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("LoanInstallmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GatewayAuthority")
                        .IsUnique()
                        .HasFilter("\"GatewayAuthority\" IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("LoanInstallmentId", "CreatedAt");

                    b.ToTable("InstallmentPayments");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("BaseSalary")
                        .HasColumnType("bigint");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LoanRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoanRequestId");

                    b.ToTable("LoanDocuments");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanInstallment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoanRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PaidMethod")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoanRequestId");

                    b.ToTable("LoanInstallments");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanPermissionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdminResponse")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LoanTypeId");

                    b.ToTable("LoanPermissionRequests");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AnnualFeePercent")
                        .HasColumnType("numeric");

                    b.Property<long>("ApprovedAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthlyPaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("RejectReason")
                        .HasColumnType("text");

                    b.Property<long>("RequestedAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequiredDocumentDescription")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresDocument")
                        .HasColumnType("boolean");

                    b.Property<long>("SettlementAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SettlementDemandedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SettlementDueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SettlementReason")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TotalPayableAmount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LoanTypeId");

                    b.ToTable("LoanRequests");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("InterestRate")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LoanTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxAmount")
                        .HasColumnType("integer");

                    b.Property<int>("MinScore")
                        .HasColumnType("integer");

                    b.Property<int>("MinWorkMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LoanTypeId");

                    b.ToTable("LoanRules");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LoanTypes");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoginHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceBrowser")
                        .HasColumnType("text");

                    b.Property<string>("DeviceOs")
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LoginHistories");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceBrowser")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("DeviceOs")
                        .HasColumnType("text");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReplacedByTokenId")
                        .HasColumnType("integer");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KasraLoan.Domain.Entities.LoanRequest", "LoanRequest")
                        .WithMany()
                        .HasForeignKey("LoanRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.Employee", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.JobPosition", "JobPosition")
                        .WithMany("Employees")
                        .HasForeignKey("JobPositionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("KasraLoan.Domain.Entities.LoanType", "ManagedLoanType")
                        .WithMany()
                        .HasForeignKey("ManagedLoanTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("JobPosition");

                    b.Navigation("ManagedLoanType");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.EmployeeScore", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.EmploymentStatusChange", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.InstallmentPayment", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KasraLoan.Domain.Entities.LoanInstallment", "LoanInstallment")
                        .WithMany("Payments")
                        .HasForeignKey("LoanInstallmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LoanInstallment");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanDocument", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.LoanRequest", "LoanRequest")
                        .WithMany("LoanDocuments")
                        .HasForeignKey("LoanRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanInstallment", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.LoanRequest", "LoanRequest")
                        .WithMany("LoanInstallments")
                        .HasForeignKey("LoanRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanPermissionRequest", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KasraLoan.Domain.Entities.LoanType", "LoanType")
                        .WithMany()
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LoanType");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanRequest", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KasraLoan.Domain.Entities.LoanType", "LoanType")
                        .WithMany("LoanRequests")
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("KasraLoan.Domain.Entities.LoanDetails", "Details", b1 =>
                        {
                            b1.Property<Guid>("LoanRequestId")
                                .HasColumnType("uuid");

                            b1.HasKey("LoanRequestId");

                            b1.ToTable("LoanRequests");

                            b1.ToJson("Details");

                            b1.WithOwner()
                                .HasForeignKey("LoanRequestId");

                            b1.OwnsOne("KasraLoan.Domain.Entities.ImmediatePaymentLoanDetails", "ImmediatePayment", b2 =>
                                {
                                    b2.Property<Guid>("LoanDetailsLoanRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Purpose")
                                        .HasColumnType("integer");

                                    b2.HasKey("LoanDetailsLoanRequestId");

                                    b2.ToTable("LoanRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanDetailsLoanRequestId");
                                });

                            b1.OwnsOne("KasraLoan.Domain.Entities.MarriageLoanDetails", "Marriage", b2 =>
                                {
                                    b2.Property<Guid>("LoanDetailsLoanRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Notes")
                                        .HasColumnType("text");

                                    b2.Property<string>("SpouseFirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("SpouseLastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("SpouseNationalId")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("LoanDetailsLoanRequestId");

                                    b2.ToTable("LoanRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanDetailsLoanRequestId");
                                });

                            b1.OwnsOne("KasraLoan.Domain.Entities.SpecialCaseLoanDetails", "SpecialCase", b2 =>
                                {
                                    b2.Property<Guid>("LoanDetailsLoanRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Category")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.HasKey("LoanDetailsLoanRequestId");

                                    b2.ToTable("LoanRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanDetailsLoanRequestId");
                                });

                            b1.OwnsOne("KasraLoan.Domain.Entities.TravelLoanDetails", "Travel", b2 =>
                                {
                                    b2.Property<Guid>("LoanDetailsLoanRequestId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Destination")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("DestinationType")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("EndDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<string>("Notes")
                                        .HasColumnType("text");

                                    b2.Property<DateTime>("StartDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("LoanDetailsLoanRequestId");

                                    b2.ToTable("LoanRequests");

                                    b2.WithOwner()
                                        .HasForeignKey("LoanDetailsLoanRequestId");
                                });

                            b1.Navigation("ImmediatePayment");

                            b1.Navigation("Marriage");

                            b1.Navigation("SpecialCase");

                            b1.Navigation("Travel");
                        });

                    b.Navigation("Details");

                    b.Navigation("Employee");

                    b.Navigation("LoanType");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanRule", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.LoanType", "LoanType")
                        .WithMany("LoanRules")
                        .HasForeignKey("LoanTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanType");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoginHistory", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.Notification", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("KasraLoan.Domain.Entities.Employee", "Employee")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.Employee", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.JobPosition", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanInstallment", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanRequest", b =>
                {
                    b.Navigation("LoanDocuments");

                    b.Navigation("LoanInstallments");
                });

            modelBuilder.Entity("KasraLoan.Domain.Entities.LoanType", b =>
                {
                    b.Navigation("LoanRequests");

                    b.Navigation("LoanRules");
                });
#pragma warning restore 612, 618
        }
    }
}
